sudo: false
addons:
  apt:
    packages:
    - libgmp-dev
matrix:
  include:
    - env: BUILD=stack GHCVER=8.10.7 STACK_YAML=stack.yaml
    - secure: Tc9dJuDBuzYjsiCPjG0udSlW6sdxJbkqKMsnmH1kUwqEjmXCfXMiqa36mPMk+wvih+iRLPb6Wt18Fu73khBrpq8AAgQrTpdC4r+gTJg5eBDlgA35lijMu1scHhGEkRnojIfvydvj9c2bUvzRPeKyYYzPqpmGgZDtSuued7R2W5ESk6axMdp0Rc+5DE9rYFV9Xrl1Vci/Sct+m70LdAewCrOC1cJuAcUq8CR8FIHRsIyE7AddiCp+uTol+GCC6GLXa79o5P36CZzgHPEo3j+tQzYIu/0uSA2RyWjGv32adEc6ETqkLUPJD+Tq+MfODMiv010vBvADzXsX2WT0dmPiYy2Kb51mjg3kVrWqBoW6zwZqA2bzntv6Jno9MfHWYpQi6GlIPxYFskGoVS+idS3rPgfG1sjomyoRE9216hu/2gurzMxoSAEq10tRgCnwl+sz7U/0im0n+wdMhytkmhC72AEQZnqlEUkOnLhDzR4AyKOS6DJNXnX0MLH0aLVbVE//tSmllRPQ3N2nuOXhuLYXVvNSggOrdoAlzZLtOc7sQOMGvnwbbZQ7TraV8Z7MBdx+MyHLazcT4zS3LKCFIrhkzn54ApnvCp2mD8o37r5KJr0SmkvOZF165W3OaprJ0wJ9IyXQa/HJgB+yLz+hucs8UKhApqK0K9DIjBzpWvj1kpw=
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack setup
- stack update
- stack build
- stack test
cache:
  directories:
  - "$HOME/.stack"
